---
- name: Override default data with user one
  set_fact:
    apprise: "{{ apprise_defaults | combine(apprise, recursive=True) }}"
  tags:
    - always

- name: Include installation tasks
  include_tasks: install.yml
  when: apprise.enabled
  tags:
    - apprise
    - install

- name: Include configuration tasks
  include_tasks: config.yml
  when: apprise.enabled
  tags:
    - apprise
    - config
